### ISSUE TITLE
Add Languages

### ISSUE THREAD

**Issue by aculligan** [aculligan/Zendesk_Priority_Highlights#4]
Add translations of default priorities.

**Comment by aculligan** [comment]
Translation needed for: 

- Dutch
- Danish
- Spanish
- French
- German
- Japanese
- Polish
- Portuguese
- Chinese

**Comment by richardvd91** [comment]
Do you have a list of all text strings that need to be translated? happy to translate to Dutch

**Comment by aculligan** [comment]
Added automatic support for: 

- Bulgarian
- Chinese (Simplified)
- Czech
- Danish
- Dutch
- English
- Finnish
- French
- German
- Greek
- Hindi
- Hungarian
- Indonesian
- Italian
- Japanese
- Korean
- Norwegian
- Polish
- Portuguese
- Romanian
- Russian
- Spanish
- Swedish
- Thai
- Turkish
- Ukrainian
- Vietnamese
